service: poc-serverless

custom:
  currentStage: ${self:service}
  parameters:
    tablePruebaTekpro: prueba_tekpro
    bucketName: config-bucket-tekpro-01

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  stackTags:
    billing_name: NN - PoC Serverless

resources:
  Resources:
    PruebaTekpro:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: prueba_tekpro
        AttributeDefinitions:
          - AttributeName: product
            AttributeType: S
        KeySchema:
          - AttributeName: product
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 50
          WriteCapacityUnits: 50
        SSESpecification:
          SSEEnabled: true
functions:
  getDynamoItem:
    handler: get-dynamo-item.handler
    events:
      - schedule:
          rate: cron(0/1 * ? * * *)
          enabled: false
    environment:
      tablePruebaTekpro: ${self:custom.parameters.tablePruebaTekpro}
  saveDataOnS3:
    handler: save-data-on-s3.handler
    environment:
      filenameDynamoData: product.json
      bucketName: ${self:custom.parameters.bucketName}
  initProcess:
    handler: init-process.handler
    environment:
      lambdaGetDynamoItem: ${self:service}-${self:provider.stage}-getDynamoItem
      lambdaSaveDataOnS3: ${self:service}-${self:provider.stage}-saveDataOnS3